# Generated by Django 5.0.1 on 2024-01-28 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AngelTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.CharField(max_length=200)),
                ('Password', models.CharField(default='Password', max_length=300)),
                ('AppID', models.CharField(blank=True, max_length=300)),
                ('APISecret', models.CharField(blank=True, max_length=300)),
                ('AccessToken', models.CharField(blank=True, max_length=1000, null=True)),
                ('RefreshToken', models.CharField(blank=True, max_length=300, null=True)),
                ('FeedToken', models.CharField(blank=True, max_length=300, null=True)),
                ('mpin', models.CharField(blank=True, max_length=10, null=True)),
                ('Comment', models.CharField(blank=True, max_length=300)),
                ('Trade', models.BooleanField(default=False)),
                ('webhook_sub', models.CharField(max_length=200, unique=True)),
                ('LastOrderTime', models.DateTimeField(blank=True, null=True)),
                ('LastOrderStatus', models.BooleanField(default=False)),
                ('ErrorMessage', models.CharField(blank=True, max_length=200, null=True)),
                ('LastLoginStatus', models.BooleanField(default=False)),
                ('LastLoginTime', models.DateTimeField(blank=True, null=True)),
                ('LastLoginMessage', models.CharField(blank=True, default='--- Password invalid--- ', max_length=200, null=True)),
                ('OpeningBalance', models.CharField(blank=True, default='Upcoming', max_length=200, null=True)),
                ('ClientName', models.CharField(blank=True, default='Not Available', max_length=200, null=True)),
                ('MobileNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('EmailID', models.CharField(blank=True, max_length=200, null=True)),
                ('ChildOrderStatusLast', models.CharField(blank=True, max_length=50, null=True)),
                ('ChildOrderTimeLast', models.DateTimeField(blank=True, null=True)),
                ('Broker', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='login.brokerlist')),
            ],
        ),
    ]
