# Generated by Django 5.0.1 on 2024-02-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angeltable',
            name='APISecret',
            field=models.CharField(blank=True, default='6SXtlX3u7Ep4LBpBM0MGyh2CHsvEdQ31Mo66PiZsytM6mzdRmphXIcp4W532BuzzOfADE3lkOAX09VV4nOH2cVCsuPuirxZSAovW', max_length=300),
        ),
        migrations.AlterField(
            model_name='angeltable',
            name='AppID',
            field=models.CharField(blank=True, default='rmLd4Q7J4RSi58y', max_length=300),
        ),
    ]
